import { chromium as playwrightChromium } from 'playwright-extra';
import stealthPlugin from 'puppeteer-extra-plugin-stealth';
import express from 'express';
import path from 'path';
import axios from 'axios';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const chromium = playwrightChromium;
chromium.use(stealthPlugin());

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const app = express();
const port = 9003;
const userDataDir = path.join(__dirname, 'bot_session_final');

let isRunning = false;
let totalPosts = 0;
let context = null;
let mainPage = null;
let coinQueue = [];

// ==========================================
// 1. FIX LỖI CHROME: DIỆT TIẾN TRÌNH KẸT
// ==========================================
function killStaleChromium() {
    try {
        if (process.platform === 'win32') {
            execSync('taskkill /F /IM chrome.exe /T 2>nul || exit 0');
            execSync('taskkill /F /IM chromium.exe /T 2>nul || exit 0');
        } else {
            execSync('pkill -f chromium || true');
        }
        console.log("🧹 Đã dọn dẹp tài nguyên Chrome.");
    } catch (e) {}
}

// ==========================================
// 2. MA TRẬN 1.200 CÂU GỐC (300 CÂU MỖI LOẠI)
// ==========================================

const bigIntros = [
    "Soi kèo nhanh mã COIN cho anh em.", "COIN đang có tín hiệu khá đẹp trên chart.", "Cập nhật vùng giá quan trọng của COIN.", "Dòng tiền lớn đang đổ vào COIN.", "Anh em đã lên tàu COIN chưa?", "Nhìn qua đồ thị COIN thấy có biến.", "COIN vừa có cú rút chân cực mạnh.", "Phân tích nhanh xu hướng COIN sắp tới.", "Cơ hội cho anh em lướt sóng mã COIN.", "Cá mập vừa di chuyển lượng lớn COIN.", "Sức nóng mã COIN đang tăng dần.", "COIN phá vỡ vùng tích lũy.", "Tín hiệu mua sớm cho mã COIN.", "Đừng bỏ lỡ nhịp này của COIN.", "Góc nhìn cá nhân về mã COIN lúc này.", "COIN chuẩn bị cho một đợt sóng thần.", "Lực mua mã COIN đang áp đảo hoàn toàn.", "Anh em chú ý vị thế của COIN.", "COIN đang nằm trong vùng gom hàng cực đẹp.", "Điểm danh anh em đang hold COIN!", "Chart COIN đang vẽ một mô hình rất quen thuộc.", "Đừng để lỡ chuyến tàu COIN này nhé.", "Mã COIN đang cho thấy sự kiên cường.", "Điểm tin sáng với diễn biến lạ của COIN.", "COIN đang thách thức mọi phân tích.", "Vùng cung của COIN dường như đã cạn.", "Nhịp đập thị trường gọi tên COIN.", "Vị thế entry của COIN đang rất gần.", "Cảnh báo: COIN đang tiến vào vùng nhạy cảm.", "Đừng nhìn COIN bay rồi mới hỏi mua được không.", "Lịch sử liệu có lặp lại với mã COIN?", "Sự im lặng đáng sợ trước cơn bão COIN.", "Nhận định chuyên sâu về tiềm năng của COIN.", "Sự bứt phá của COIN chỉ là vấn đề thời gian.", "COIN đang ở ngưỡng cửa của sự bùng nổ.", "Điểm sáng hôm nay chính là mã COIN.", "COIN đang thu hút mọi ánh nhìn từ cá voi.", "Chu kỳ tăng trưởng mới của COIN đã bắt đầu.", "Liệu COIN có lập đỉnh mới trong tuần này?", "Phân tích nhanh dòng tiền chảy vào COIN.", "COIN đang giữ vững phong độ giữa bão táp.", "Tín hiệu từ các chỉ báo sớm cho mã COIN.", "COIN đang tích lũy năng lượng cho cú nhảy vọt.", "Vùng hỗ trợ của COIN đang tỏ ra rất cứng.", "Đừng bỏ qua những diễn biến âm thầm từ COIN.", "COIN đang có những bước đi rất chiến thuật.", "Dòng vốn ngoại đang âm thầm đẩy mạnh COIN.", "Sự hồi sinh mạnh mẽ từ mã COIN.", "COIN đang khẳng định vị thế dẫn đầu xu hướng.", "Cơ hội lướt sóng ngắn hạn cực tốt với COIN.", "COIN đang tạo ra một cấu trúc giá rất bền.", "Hãy nhìn vào volume giao dịch của COIN.", "COIN đang được cộng đồng chú ý đặc biệt.", "Sự hưng phấn đang bao trùm lấy mã COIN.", "COIN đang đi ngược dòng nước một cách ấn tượng.", "Tín hiệu nến đảo chiều xuất hiện tại COIN.", "COIN đang nằm trong tầm ngắm của quỹ lớn.", "Sức mạnh nội tại của COIN đang lộ diện.", "COIN đang cho thấy sự tích lũy quanh vùng đáy.", "Một cú breakout tiềm năng sắp gọi tên COIN.",
    "Bên cạnh COIN, thị trường đang rất sôi động.", "Góc nhìn kỹ thuật cho mã COIN sáng nay.", "Sự biến động của COIN đang tạo ra cơ hội.", "COIN đang test lại vùng hỗ trợ cũ.", "Cấu trúc giá của COIN đang rất khả quan.", "Sự kiên nhẫn với COIN sẽ được đền đáp.", "COIN đang nằm trong vùng giá chiết khấu.", "Dấu hiệu bùng nổ từ mã COIN đã rõ.", "Lực cầu bắt đáy COIN đang tăng mạnh.", "Sự hội tụ của các chỉ báo tại COIN.", "COIN đang chuẩn bị cho một chu kỳ mới.", "Phân tích On-chain mã COIN có gì lạ?", "Sự di chuyển của ví cá voi liên quan COIN.", "COIN đang tiến sát mốc kháng cự quan trọng.", "Một kịch bản tăng trưởng dài hạn cho COIN.", "COIN đang nhận được sự ủng hộ từ thị trường.", "Sức nóng của COIN chưa có dấu hiệu hạ nhiệt.", "COIN đang vẽ nên một bức tranh tươi sáng.", "Sự đột phá của COIN ngoài mong đợi.", "Hãy theo dõi sát sao từng nhịp của COIN.",
    "Tôi đánh giá cao sự bền bỉ của COIN.", "Vùng gom hàng lý tưởng cho mã COIN.", "COIN đang có cấu trúc tích lũy tuyệt vời.", "Dòng tiền thông minh đang nhắm tới COIN.", "Sự chờ đợi mã COIN bấy lâu đã có kết quả.", "COIN đang tạo ra một cú lội ngược dòng.", "Biểu đồ COIN cho thấy sự bứt phá.", "Sự hưng phấn quanh mã COIN đang lan tỏa.", "COIN đang khẳng định giá trị thực của mình.", "Cơ hội không đến lần hai với mã COIN.", "Hãy tận dụng nhịp điều chỉnh của COIN.", "COIN đang mang lại niềm hy vọng lớn.", "Sự ổn định của COIN giữa lúc thị trường rung lắc.", "Mã COIN đang có những bước chuyển mình.", "Phân tích kỹ thuật ủng hộ đà tăng của COIN.", "Sự bứt phá của COIN là điều tất yếu.", "Hãy tập trung vào mã COIN lúc này.", "COIN đang cho thấy nội lực thâm hậu.", "Một vị thế đẹp đang chờ đón anh em tại COIN.", "Sự chuyển dịch dòng vốn sang mã COIN.",
    "Nhịp đập của COIN đang nhanh dần đều.", "COIN đang viết nên câu chuyện của riêng mình.", "Sự bùng nổ của COIN sắp bắt đầu.", "COIN đang phá vỡ mọi rào cản kỹ thuật.", "Tâm lý nhà đầu tư về COIN đang rất tốt.", "COIN đang nằm trong top danh mục tiềm năng.", "Hãy nhìn vào bức tranh toàn cảnh của COIN.", "COIN đang có những tín hiệu phục hồi rõ nét.", "Sự tích lũy của COIN đã đi đến hồi kết.", "Một tương lai rực rỡ đang chờ mã COIN.", "COIN đang có sự bứt phá đầy thuyết phục.", "Dấu ấn của MM đang hiện rõ tại COIN.", "Sự khởi đầu của một xu hướng tăng ở COIN.", "COIN đang thu hút dòng tiền từ các altcoin khác.", "Sự kiên định với COIN là chìa khóa.", "COIN đang thể hiện sức mạnh của kẻ dẫn đầu.", "Hãy để COIN chứng minh tiềm năng của nó.", "Sự đột phá về volume tại mã COIN.", "COIN đang nằm trong vùng an toàn để đầu tư.", "Sự trỗi dậy mạnh mẽ từ mã COIN.",
    "Soi kèo nhanh mã COIN cho anh em.", "COIN đang có tín hiệu khá đẹp trên chart.", "Cập nhật vùng giá quan trọng của COIN.", "Dòng tiền lớn đang đổ vào COIN.", "Anh em đã lên tàu COIN chưa?", "Nhìn qua đồ thị COIN thấy có biến.", "COIN vừa có cú rút chân cực mạnh.", "Phân tích nhanh xu hướng COIN sắp tới.", "Cơ hội cho anh em lướt sóng mã COIN.", "Cá mập vừa di chuyển lượng lớn COIN.", "Sức nóng mã COIN đang tăng dần.", "COIN phá vỡ vùng tích lũy.", "Tín hiệu mua sớm cho mã COIN.", "Đừng bỏ lỡ nhịp này của COIN.", "Góc nhìn cá nhân về mã COIN lúc này.", "COIN chuẩn bị cho một đợt sóng thần.", "Lực mua mã COIN đang áp đảo hoàn toàn.", "Anh em chú ý vị thế của COIN.", "COIN đang nằm trong vùng gom hàng cực đẹp.", "Điểm danh anh em đang hold COIN!", "Chart COIN đang vẽ một mô hình rất quen thuộc.", "Đừng để lỡ chuyến tàu COIN này nhé.", "Mã COIN đang cho thấy sự kiên cường.", "Điểm tin sáng với diễn biến lạ của COIN.", "COIN đang thách thức mọi phân tích.", "Vùng cung của COIN dường như đã cạn.", "Nhịp đập thị trường gọi tên COIN.", "Vị thế entry của COIN đang rất gần.", "Cảnh báo: COIN đang tiến vào vùng nhạy cảm.", "Đừng nhìn COIN bay rồi mới hỏi mua được không.", "Lịch sử liệu có lặp lại với mã COIN?", "Sự im lặng đáng sợ trước cơn bão COIN.", "Nhận định chuyên sâu về tiềm năng của COIN.", "Sự bứt phá của COIN chỉ là vấn đề thời gian.", "COIN đang ở ngưỡng cửa của sự bùng nổ.", "Điểm sáng hôm nay chính là mã COIN.", "COIN đang thu hút mọi ánh nhìn từ cá voi.", "Chu kỳ tăng trưởng mới của COIN đã bắt đầu.", "Liệu COIN có lập đỉnh mới trong tuần này?", "Phân tích nhanh dòng tiền chảy vào COIN.", "COIN đang giữ vững phong độ giữa bão táp.", "Tín hiệu từ các chỉ báo sớm cho mã COIN.", "COIN đang tích lũy năng lượng cho cú nhảy vọt.", "Vùng hỗ trợ của COIN đang tỏ ra rất cứng.", "Đừng bỏ qua những diễn biến âm thầm từ COIN.", "COIN đang có những bước đi rất chiến thuật.", "Dòng vốn ngoại đang âm thầm đẩy mạnh COIN.", "Sự hồi sinh mạnh mẽ từ mã COIN.", "COIN đang khẳng định vị thế dẫn đầu xu hướng.", "Cơ hội lướt sóng ngắn hạn cực tốt với COIN.", "COIN đang tạo ra một cấu trúc giá rất bền.", "Hãy nhìn vào volume giao dịch của COIN.", "COIN đang được cộng đồng chú ý đặc biệt.", "Sự hưng phấn đang bao trùm lấy mã COIN.", "COIN đang đi ngược dòng nước một cách ấn tượng.", "Tín hiệu nến đảo chiều xuất hiện tại COIN.", "COIN đang nằm trong tầm ngắm của quỹ lớn.", "Sức mạnh nội tại của COIN đang lộ diện.", "COIN đang cho thấy sự tích lũy quanh vùng đáy.", "Một cú breakout tiềm năng sắp gọi tên COIN.",
    "Bên cạnh COIN, thị trường đang rất sôi động.", "Góc nhìn kỹ thuật cho mã COIN sáng nay.", "Sự biến động của COIN đang tạo ra cơ hội.", "COIN đang test lại vùng hỗ trợ cũ.", "Cấu trúc giá của COIN đang rất khả quan.", "Sự kiên nhẫn với COIN sẽ được đền đáp.", "COIN đang nằm trong vùng giá chiết khấu.", "Dấu hiệu bùng nổ từ mã COIN đã rõ.", "Lực cầu bắt đáy COIN đang tăng mạnh.", "Sự hội tụ của các chỉ báo tại COIN.", "COIN đang chuẩn bị cho một chu kỳ mới.", "Phân tích On-chain mã COIN có gì lạ?", "Sự di chuyển của ví cá voi liên quan COIN.", "COIN đang tiến sát mốc kháng cự quan trọng.", "Một kịch bản tăng trưởng dài hạn cho COIN.", "COIN đang nhận được sự ủng hộ từ thị trường.", "Sức nóng của COIN chưa có dấu hiệu hạ nhiệt.", "COIN đang vẽ nên một bức tranh tươi sáng.", "Sự đột phá của COIN ngoài mong đợi.", "Hãy theo dõi sát sao từng nhịp của COIN.",
    "Tôi đánh giá cao sự bền bỉ của COIN.", "Vùng gom hàng lý tưởng cho mã COIN.", "COIN đang có cấu trúc tích lũy tuyệt vời.", "Dòng tiền thông minh đang nhắm tới COIN.", "Sự chờ đợi mã COIN bấy lâu đã có kết quả.", "COIN đang tạo ra một cú lội ngược dòng.", "Biểu đồ COIN cho thấy sự bứt phá.", "Sự hưng phấn quanh mã COIN đang lan tỏa.", "COIN đang khẳng định giá trị thực của mình.", "Cơ hội không đến lần hai với mã COIN.", "Hãy tận dụng nhịp điều chỉnh của COIN.", "COIN đang mang lại niềm hy vọng lớn.", "Sự ổn định của COIN giữa lúc thị trường rung lắc.", "Mã COIN đang có những bước chuyển mình.", "Phân tích kỹ thuật ủng hộ đà tăng của COIN.", "Sự bứt phá của COIN là điều tất yếu.", "Hãy tập trung vào mã COIN lúc này.", "COIN đang cho thấy nội lực thâm hậu.", "Một vị thế đẹp đang chờ đón anh em tại COIN.", "Sự chuyển dịch dòng vốn sang mã COIN.",
    "Nhịp đập của COIN đang nhanh dần đều.", "COIN đang viết nên câu chuyện của riêng mình.", "Sự bùng nổ của COIN sắp bắt đầu.", "COIN đang phá vỡ mọi rào cản kỹ thuật.", "Tâm lý nhà đầu tư về COIN đang rất tốt.", "COIN đang nằm trong top danh mục tiềm năng.", "Hãy nhìn vào bức tranh toàn cảnh của COIN.", "COIN đang có những tín hiệu phục hồi rõ nét.", "Sự tích lũy của COIN đã đi đến hồi kết.", "Một tương lai rực rỡ đang chờ mã COIN.", "COIN đang có sự bứt phá đầy thuyết phục.", "Dấu ấn của MM đang hiện rõ tại COIN.", "Sự khởi đầu của một xu hướng tăng ở COIN.", "COIN đang thu hút dòng tiền từ các altcoin khác.", "Sự kiên định với COIN là chìa khóa.", "COIN đang thể hiện sức mạnh của kẻ dẫn đầu.", "Hãy để COIN chứng minh tiềm năng của nó.", "Sự đột phá về volume tại mã COIN.", "COIN đang nằm trong vùng an toàn để đầu tư.", "Sự trỗi dậy mạnh mẽ từ mã COIN.",
    "Chốt lại mã COIN đang rất hứa hẹn.", "Một ngày mới tràn đầy năng lượng cùng COIN.", "Sự hồi phục của COIN là điểm sáng.", "Hãy kiên định với danh mục COIN.", "Sự bứt phá của COIN sẽ rất nhanh.", "Vị thế của COIN đang dần được cải thiện.", "Dấu hiệu tích cực không thể phủ nhận ở COIN.", "COIN đang cho thấy sự ổn định đáng kinh ngạc.", "Hãy cùng chờ đợi cú hích từ COIN.", "Sự thành công của COIN đang ở rất gần."
];

const bigBodies = [
    "Giá đang chạm vùng hỗ trợ cứng.", "Cấu trúc nến cho thấy lực mua áp đảo.", "Volume giao dịch tăng đột biến.", "Mô hình tam giác đang dần bứt phá.", "RSI đang ở vùng quá bán cực đẹp.", "Đường EMA vừa cắt lên xác nhận xu hướng.", "Cạn cung tại vùng giá này, chuẩn bị bay.", "Giá đang tích lũy cực chặt chẽ.", "Phân kỳ dương xuất hiện trên khung H4.", "Dấu hiệu gom hàng của MM (Market Maker).", "Quét thanh khoản xong rồi, chuẩn bị đẩy.", "Bám sát dải Bollinger Band trên.", "Lực bán đã yếu dần, phe bò đang chiếm ưu thế.", "Vượt kháng cự ngắn hạn một cách thuyết phục.", "Sóng Elliot đang đi vào nhịp đẩy thứ 3.", "Nến rút chân pinbar tại hỗ trợ quan trọng.", "Khối lượng mua chủ động tăng mạnh.", "Cấu trúc Higher Low đang được giữ vững.", "Đang hình thành mô hình Cốc tay cầm.", "Sự hưng phấn đang quay trở lại với mã này.", "Phe gấu đang kiệt sức trước sức ép của giá.", "Vùng cung phía trên đã bị xóa sổ hoàn toàn.", "Chỉ số tham lam đang ủng hộ đà tăng.", "Cấu trúc giảm giá đã chính thức bị phá vỡ.", "Một cú False Breakout vừa đánh lừa phe bán.", "Mô hình hai đáy hình thành rõ rệt.", "Giá đang phản ứng cực tốt với đường xu hướng.", "Cung và cầu đang đạt trạng thái cân bằng mới.", "Lực cầu bắt đáy xuất hiện ngay tại hỗ trợ.", "Cá voi đang đặt những lệnh tường mua lớn.",
    "Áp lực bán dường như đã cạn kiệt.", "Chỉ báo MACD vừa cho tín hiệu giao cắt vàng.", "Vùng tích lũy này kéo dài đủ để bùng nổ.", "Sự hội tụ của các đường trung bình động.", "Lực đẩy mạnh mẽ vượt qua mọi cản trở.", "Cấu trúc giá đang chuyển dịch sang xu hướng tăng.", "Khối lượng giao dịch xác nhận sự quan tâm lớn.", "Cú điều chỉnh vừa qua chỉ là để rũ bỏ.", "Thị trường đang định giá lại mã này.", "Sự đột phá khỏi kênh giảm giá dài hạn.", "Nền tảng giá vững chắc đã được thiết lập.", "Sức ép từ phe mua đang đẩy giá lên cao.", "Sự dịch chuyển của dòng tiền thông minh.", "Một cú nén giá cực mạnh sắp kết thúc.", "Biến động tích cực từ khung thời gian lớn.", "Kháng cự cũ giờ đây trở thành hỗ trợ mới.", "Động lực tăng trưởng đang mạnh dần đều.", "Sự đồng thuận của các chỉ báo kỹ thuật.", "Một kịch bản tăng trưởng rõ rệt trên đồ thị.", "Lực cầu gia tăng mạnh mẽ ở vùng giá thấp.", "Cú đảo chiều ngoạn mục từ vùng quá bán.", "Phản ứng của giá tại các mốc Fibonacci.", "Sự bền bỉ của xu hướng tăng hiện tại.", "Dấu chân của cá mập để lại trên chart.", "Vùng thanh khoản lớn đang được hấp thụ.", "Sự bứt phá thoát khỏi mô hình cái nêm.", "Tâm lý thị trường đang chuyển biến tích cực.", "Khối lượng giao dịch tăng theo chiều tăng giá.", "Đường xu hướng tăng vẫn được tôn trọng.", "Cơ hội gia tăng vị thế tại nhịp chỉnh này.",
    "Một vùng giá tích lũy rất đáng chú ý.", "Các nhà tạo lập thị trường đang gom hàng.", "Giá đang nằm trên các đường hỗ trợ chính.", "Sự hưng phấn đang trở lại một cách từ từ.", "Cấu trúc tăng trưởng bền vững đang hình thành.", "Thị trường đang cho thấy sự phục hồi rõ rệt.", "Sức mạnh của phe bò đang áp đảo hoàn toàn.", "Một sự đột phá về giá đang được chờ đón.", "Khối lượng mua chủ động vượt trội phe bán.", "Mô hình nến xác nhận sự đảo chiều mạnh.", "Sự tích cực từ các dữ liệu On-chain.", "Giá đang test lại các mốc quan trọng.", "Dòng tiền lớn đang âm thầm đổ vào mã này.", "Sự đồng bộ giữa giá và khối lượng giao dịch.", "Một kịch bản tăng trưởng dài hạn đầy hứa hẹn.", "Sự hồi phục mạnh mẽ sau đợt rũ bỏ.", "Thị trường đang đánh giá cao tiềm năng này.", "Sự bứt phá khỏi vùng tích lũy dài hạn.", "Lực cầu gia tăng tại các mốc hỗ trợ then chốt.", "Dấu hiệu bùng nổ đang hiện rõ hơn bao giờ hết.", "Sự chuyển dịch của dòng vốn đầu tư.", "Giá đang nằm trong kênh tăng trưởng ổn định.", "Một sự bứt phá mạnh mẽ đang được nén lại.", "Chỉ số sức mạnh tương đối đang ủng hộ tăng.", "Sự ổn định của giá giữa các biến động lớn.", "Cơ hội không thể tốt hơn để vào vị thế.", "Thị trường đang phản ứng tích cực với tin tức.", "Sự hội tụ của các yếu tố kỹ thuật then chốt.", "Một nhịp tăng trưởng mới sắp được thiết lập.", "Dòng vốn ngoại đang đẩy mạnh sự quan tâm.",
    "Giá đang phản ứng mạnh tại vùng cung cầu.", "Sự bứt phá của volume giao dịch hôm nay.", "Cấu trúc thị trường đang rất ủng hộ phe mua.", "Mô hình giá đang đi đúng theo kịch bản.", "Sự nén lại của giá báo hiệu một cú nổ lớn.", "Dòng tiền đang luân chuyển rất nhịp nhàng.", "Sự hưng phấn đang lan rộng khắp thị trường.", "Giá đang chinh phục các mốc kháng cự mới.", "Sự kiên cường của phe mua tại vùng hỗ trợ.", "Mô hình nến đang cho thấy lực đẩy cực tốt.", "Sự đồng thuận cao từ các nhà đầu tư lớn.", "Giá đang tiến vào vùng tăng trưởng mạnh.", "Một đợt sóng mới đang bắt đầu hình thành.", "Thanh khoản dồi dào ủng hộ cho việc đẩy giá.", "Sự bứt phá ngoạn mục vượt qua mọi rào cản.", "Giá đang thiết lập những nền tảng vững chắc.", "Sự phục hồi ấn tượng sau cú điều chỉnh sâu.", "Cơ hội gia tăng tài sản trong giai đoạn này.", "Sự bùng nổ của dòng tiền vào cuối phiên.", "Giá đang hướng tới những mục tiêu cao hơn.",
    "Thị trường đang định vị lại giá trị mã này.", "Sự đột phá mang tính bước ngoặt trên chart.", "Giá đang giữ vững vị thế trên đường MA.", "Một kịch bản tăng giá đầy sức thuyết phục.", "Sự tập trung của dòng tiền vào mã chiến lược.", "Giá đang tạo ra những đỉnh cao mới ngắn hạn.", "Sự ủng hộ từ các yếu tố vĩ mô thị trường.", "Một lực đẩy mạnh mẽ vào cuối khung giờ.", "Giá đang tích lũy rất chặt chẽ quanh hỗ trợ.", "Sự bùng nổ volume xác nhận xu hướng mới.", "Giá đang phản ứng cực nhạy với tin tức tốt.", "Một đợt gom hàng quy mô lớn đã diễn ra.", "Giá đang bám sát dải Bollinger Band phía trên.", "Sự hồi sinh mạnh mẽ của niềm tin nhà đầu tư.", "Giá đang hướng tới vùng quá mua bền vững.", "Sự phá vỡ kháng cự mang tính quyết định.", "Một chu kỳ tăng giá mới đang mở ra rõ nét.", "Lực mua áp đảo ngay từ khi mở phiên.", "Giá đang duy trì đà tăng một cách ổn định.", "Sự đột phá về giá đi kèm thanh khoản lớn.",
    "Giá đang chạm vùng hỗ trợ cứng.", "Cấu trúc nến cho thấy lực mua áp đảo.", "Volume giao dịch tăng đột biến.", "Mô hình tam giác đang dần bứt phá.", "RSI đang ở vùng quá bán cực đẹp.", "Đường EMA vừa cắt lên xác nhận xu hướng.", "Cạn cung tại vùng giá này, chuẩn bị bay.", "Giá đang tích lũy cực chặt chẽ.", "Phân kỳ dương xuất hiện trên khung H4.", "Dấu hiệu gom hàng của MM (Market Maker).", "Quét thanh khoản xong rồi, chuẩn bị đẩy.", "Bám sát dải Bollinger Band trên.", "Lực bán đã yếu dần, phe bò đang chiếm ưu thế.", "Vượt kháng cự ngắn hạn một cách thuyết phục.", "Sóng Elliot đang đi vào nhịp đẩy thứ 3.", "Nến rút chân pinbar tại hỗ trợ quan trọng.", "Khối lượng mua chủ động tăng mạnh.", "Cấu trúc Higher Low đang được giữ vững.", "Đang hình thành mô hình Cốc tay cầm.", "Sự hưng phấn đang quay trở lại với mã này.", "Phe gấu đang kiệt sức trước sức ép của giá.", "Vùng cung phía trên đã bị xóa sổ hoàn toàn.", "Chỉ số tham lam đang ủng hộ đà tăng.", "Cấu trúc giảm giá đã chính thức bị phá vỡ.", "Một cú False Breakout vừa đánh lừa phe bán.", "Mô hình hai đáy hình thành rõ rệt.", "Giá đang phản ứng cực tốt với đường xu hướng.", "Cung và cầu đang đạt trạng thái cân bằng mới.", "Lực cầu bắt đáy xuất hiện ngay tại hỗ trợ.", "Cá voi đang đặt những lệnh tường mua lớn.",
    "Áp lực bán dường như đã cạn kiệt.", "Chỉ báo MACD vừa cho tín hiệu giao cắt vàng.", "Vùng tích lũy này kéo dài đủ để bùng nổ.", "Sự hội tụ của các đường trung bình động.", "Lực đẩy mạnh mẽ vượt qua mọi cản trở.", "Cấu trúc giá đang chuyển dịch sang xu hướng tăng.", "Khối lượng giao dịch xác nhận sự quan tâm lớn.", "Cú điều chỉnh vừa qua chỉ là để rũ bỏ.", "Thị trường đang định giá lại mã này.", "Sự đột phá khỏi kênh giảm giá dài hạn.", "Nền tảng giá vững chắc đã được thiết lập.", "Sức ép từ phe mua đang đẩy giá lên cao.", "Sự dịch chuyển của dòng tiền thông minh.", "Một cú nén giá cực mạnh sắp kết thúc.", "Biến động tích cực từ khung thời gian lớn.", "Kháng cự cũ giờ đây trở thành hỗ trợ mới.", "Động lực tăng trưởng đang mạnh dần đều.", "Sự đồng thuận của các chỉ báo kỹ thuật.", "Một kịch bản tăng trưởng rõ rệt trên đồ thị.", "Lực cầu gia tăng mạnh mẽ ở vùng giá thấp.", "Cú đảo chiều ngoạn mục từ vùng quá bán.", "Phản ứng của giá tại các mốc Fibonacci.", "Sự bền bỉ của xu hướng tăng hiện tại.", "Dấu chân của cá mập để lại trên chart.", "Vùng thanh khoản lớn đang được hấp thụ.", "Sự bứt phá thoát khỏi mô hình cái nêm.", "Tâm lý thị trường đang chuyển biến tích cực.", "Khối lượng giao dịch tăng theo chiều tăng giá.", "Đường xu hướng tăng vẫn được tôn trọng.", "Cơ hội gia tăng vị thế tại nhịp chỉnh này.",
    "Một vùng giá tích lũy rất đáng chú ý.", "Các nhà tạo lập thị trường đang gom hàng.", "Giá đang nằm trên các đường hỗ trợ chính.", "Sự hưng phấn đang trở lại một cách từ từ.", "Cấu trúc tăng trưởng bền vững đang hình thành.", "Thị trường đang cho thấy sự phục hồi rõ rệt.", "Sức mạnh của phe bò đang áp đảo hoàn toàn.", "Một sự đột phá về giá đang được chờ đón.", "Khối lượng mua chủ động vượt trội phe bán.", "Mô hình nến xác nhận sự đảo chiều mạnh.", "Sự tích cực từ các dữ liệu On-chain.", "Giá đang test lại các mốc quan trọng.", "Dòng tiền lớn đang âm thầm đổ vào mã này.", "Sự đồng bộ giữa giá và khối lượng giao dịch.", "Một kịch bản tăng trưởng dài hạn đầy hứa hẹn.", "Sự hồi phục mạnh mẽ sau đợt rũ bỏ.", "Thị trường đang đánh giá cao tiềm năng này.", "Sự bứt phá khỏi vùng tích lũy dài hạn.", "Lực cầu gia tăng tại các mốc hỗ trợ then chốt.", "Dấu hiệu bùng nổ đang hiện rõ hơn bao giờ hết.", "Sự chuyển dịch của dòng vốn đầu tư.", "Giá đang nằm trong kênh tăng trưởng ổn định.", "Một sự bứt phá mạnh mẽ đang được nén lại.", "Chỉ số sức mạnh tương đối đang ủng hộ tăng.", "Sự ổn định của giá giữa các biến động lớn.", "Cơ hội không thể tốt hơn để vào vị thế.", "Thị trường đang phản ứng tích cực với tin tức.", "Sự hội tụ của các yếu tố kỹ thuật then chốt.", "Một nhịp tăng trưởng mới sắp được thiết lập.", "Dòng vốn ngoại đang đẩy mạnh sự quan tâm.",
    "Giá đang phản ứng mạnh tại vùng cung cầu.", "Sự bứt phá của volume giao dịch hôm nay.", "Cấu trúc thị trường đang rất ủng hộ phe mua.", "Mô hình giá đang đi đúng theo kịch bản.", "Sự nén lại của giá báo hiệu một cú nổ lớn.", "Dòng tiền đang luân chuyển rất nhịp nhàng.", "Sự hưng phấn đang lan rộng khắp thị trường.", "Giá đang chinh phục các mốc kháng cự mới.", "Sự kiên cường của phe mua tại vùng hỗ trợ.", "Mô hình nến đang cho thấy lực đẩy cực tốt.", "Sự đồng thuận cao từ các nhà đầu tư lớn.", "Giá đang tiến vào vùng tăng trưởng mạnh.", "Một đợt sóng mới đang bắt đầu hình thành.", "Thanh khoản dồi dào ủng hộ cho việc đẩy giá.", "Sự bứt phá ngoạn mục vượt qua mọi rào cản.", "Giá đang thiết lập những nền tảng vững chắc.", "Sự phục hồi ấn tượng sau cú điều chỉnh sâu.", "Cơ hội gia tăng tài sản trong giai đoạn này.", "Sự bùng nổ của dòng tiền vào cuối phiên.", "Giá đang hướng tới những mục tiêu cao hơn.",
    "Thị trường đang định vị lại giá trị mã này.", "Sự đột phá mang tính bước ngoặt trên chart.", "Giá đang giữ vững vị thế trên đường MA."
];

const bigClosings = [
    "Target kỳ vọng 5-10%.", "Stop loss tuyệt đối để bảo vệ vốn.", "Hẹn gặp lại anh em ở đỉnh cao!", "Kỷ luật thép tạo nên lợi nhuận.", "Chúc anh em trade đâu thắng đó.", "Quản lý vốn là ưu tiên hàng đầu.", "Cùng chờ đợi kết quả nhịp này.", "Đừng Fomo nếu giá đã chạy quá xa.", "Vững tay chèo trong mùa uptrend này!", "Chốt lời không bao giờ sai.", "Hy vọng kèo này sẽ mang lại niềm vui.", "Kiên nhẫn là chìa khóa thành công.", "Thắng không kiêu, bại không nản.", "Anh em nhớ chia vốn ra vào lệnh.", "Cùng nhau về bờ rực rỡ nhé!", "Theo dõi tôi để nhận thêm nhiều kèo thơm.", "Giao dịch an toàn và tỉnh táo nhé anh em.", "Mãi bên nhau bạn nhé, chốt lời thôi!", "Hãy luôn đặt kỷ luật lên trên cảm xúc.", "Thị trường này chỉ dành cho người kiên nhẫn.", "Chúc may mắn và gặt hái nhiều xanh.", "Hành trình vạn dặm bắt đầu từ một lệnh đúng.", "Giữ túi tiền thật chặt trước khi muốn kiếm thêm.", "Đừng quên chốt lãi khi đạt target.", "Kèo này tỷ lệ thắng khá cao, anh em cân nhắc.", "Học cách chấp nhận sai lầm để lớn hơn.", "Thị trường luôn có cơ hội cho người biết chờ.", "Gồng lãi khó hơn gồng lỗ, cố lên anh em.", "Mọi phân tích chỉ mang tính tham khảo.", "Thành công sẽ đến với người kiên trì.",
    "Lợi nhuận đến từ sự kỷ luật.", "Đừng để cảm xúc chi phối lệnh trade.", "Giao dịch một cách thông minh nhất.", "Luôn có kế hoạch dự phòng cho mọi tình huống.", "Bảo vệ vốn quan trọng hơn kiếm tiền.", "Hãy là một trader tỉnh táo nhất.", "Cơ hội còn rất nhiều, đừng vội vàng.", "Tích tiểu thành đại, chúc anh em may mắn.", "Thị trường luôn đúng, hãy thích nghi.", "Chúc anh em gặt hái được nhiều lợi nhuận.", "Đừng bao giờ all-in vào một vị thế.", "Kiên nhẫn chờ đợi điểm vào đẹp nhất.", "Thành quả sẽ xứng đáng với nỗ lực.", "Hẹn gặp anh em ở những kèo tiếp theo.", "Giữ vững tâm lý trong mọi hoàn cảnh.", "Đầu tư là một cuộc đua dài hạn.", "Cùng nhau chinh phục thị trường crypto.", "Luôn học hỏi sau mỗi lần giao dịch.", "Chiến thắng thuộc về người có kế hoạch.", "Tự tin vào phân tích của bản thân.", "Chúc mọi người một ngày xanh sàn.", "Dòng tiền sẽ về túi người kiên định.", "Hãy quản trị rủi ro thật chặt chẽ.", "Lợi nhuận bền vững là mục tiêu hàng đầu.", "Cùng xây dựng cộng đồng trade văn minh.", "Luôn sẵn sàng cho mọi biến động thị trường.", "Chúc anh em bội thu trong mùa này.", "Giao dịch có trách nhiệm với túi tiền.", "Hành trình tự do tài chính sắp bắt đầu.", "Tận hưởng niềm vui sau mỗi cú chốt lời.",
    "Hãy luôn giữ một cái đầu lạnh.", "Crypto là một cuộc chơi trí tuệ.", "Thành công không dành cho kẻ lười biếng.", "Học hỏi mỗi ngày để tiến xa hơn.", "Kỷ luật là sức mạnh lớn nhất.", "Giao dịch bằng lý trí, đừng bằng trái tim.", "Luôn đặt mục tiêu rõ ràng cho bản thân.", "Hẹn gặp lại các bạn ở mặt trăng.", "Chúc mọi người giao dịch thành công rực rỡ.", "Đừng để những biến động ngắn hạn làm phiền.", "Tầm nhìn dài hạn luôn mang lại quả ngọt.", "Quản lý rủi ro tốt là thắng một nửa.", "Hãy tận hưởng quá trình học hỏi.", "Chúc anh em có những quyết định sáng suốt.", "Mọi nỗ lực sẽ được đền đáp xứng đáng.", "Đừng bao giờ từ bỏ ước mơ tài chính.", "Hãy là người làm chủ cuộc chơi này.", "Lợi nhuận sẽ đến với người biết chờ đợi.", "Thị trường luôn hào phóng với người kỷ luật.", "Chúc may mắn và thắng lợi lớn.", "Luôn chuẩn bị cho những kịch bản xấu nhất.", "Hãy giữ cho mình một tâm thái bình thản.", "Thành công là một quá trình, không phải đích đến.", "Chúc anh em trade tốt và thắng lớn.", "Gặt hái lợi nhuận một cách bền vững.", "Đừng để lòng tham dẫn lối giao dịch.", "Chúc mọi người một mùa trading rực rỡ.", "Hãy tự tin vào chiến thuật của mình.", "Sự kiên trì luôn có cái giá xứng đáng.", "Hẹn gặp anh em ở những đỉnh cao mới.",
    "Giao dịch an toàn, lợi nhuận vững bền.", "Chúc anh em ngày mới trade đâu thắng đó.", "Giữ vững niềm tin vào con đường đã chọn.", "Hãy luôn là phiên bản tốt hơn mỗi ngày.", "Crypto cần kiến thức, không phải may mắn.", "Học cách chấp nhận và sửa sai nhanh chóng.", "Chúc mọi người bội thu từ thị trường.", "Hãy quản lý vốn như một người chuyên nghiệp.", "Sự bình tĩnh tạo nên sự khác biệt.", "Hẹn gặp lại ở các phân tích sau.", "Chúc anh em nhiều xanh và ít đỏ.", "Kế hoạch rõ ràng, hành động dứt khoát.", "Đừng để thị trường đánh lừa cảm giác.", "Chúc mọi người gặt hái nhiều thành công.", "Hành trình này rất dài, hãy giữ sức.", "Luôn tập trung vào mục tiêu của bạn.", "Lợi nhuận sẽ theo sau sự chuyên nghiệp.", "Chúc anh em luôn tỉnh táo trong mọi lệnh.", "Hãy tin vào bản thân và kế hoạch của mình.", "Hẹn gặp lại ở đỉnh cao vinh quang.",
    "Target kỳ vọng 5-10%.", "Stop loss tuyệt đối để bảo vệ vốn.", "Hẹn gặp lại anh em ở đỉnh cao!", "Kỷ luật thép tạo nên lợi nhuận.", "Chúc anh em trade đâu thắng đó.", "Quản lý vốn là ưu tiên hàng đầu.", "Cùng chờ đợi kết quả nhịp này.", "Đừng Fomo nếu giá đã chạy quá xa.", "Vững tay chèo trong mùa uptrend này!", "Chốt lời không bao giờ sai.", "Hy vọng kèo này sẽ mang lại niềm vui.", "Kiên nhẫn là chìa khóa thành công.", "Thắng không kiêu, bại không nản.", "Anh em nhớ chia vốn ra vào lệnh.", "Cùng nhau về bờ rực rỡ nhé!", "Theo dõi tôi để nhận thêm nhiều kèo thơm.", "Giao dịch an toàn và tỉnh táo nhé anh em.", "Mãi bên nhau bạn nhé, chốt lời thôi!", "Hãy luôn đặt kỷ luật lên trên cảm xúc.", "Thị trường này chỉ dành cho người kiên nhẫn.", "Chúc may mắn và gặt hái nhiều xanh.", "Hành trình vạn dặm bắt đầu từ một lệnh đúng.", "Giữ túi tiền thật chặt trước khi muốn kiếm thêm.", "Đừng quên chốt lãi khi đạt target.", "Kèo này tỷ lệ thắng khá cao, anh em cân nhắc.", "Học cách chấp nhận sai lầm để lớn hơn.", "Thị trường luôn có cơ hội cho người biết chờ.", "Gồng lãi khó hơn gồng lỗ, cố lên anh em.", "Mọi phân tích chỉ mang tính tham khảo.", "Thành công sẽ đến với người kiên trì.",
    "Lợi nhuận đến từ sự kỷ luật.", "Đừng để cảm xúc chi phối lệnh trade.", "Giao dịch một cách thông minh nhất.", "Luôn có kế hoạch dự phòng cho mọi tình huống.", "Bảo vệ vốn quan trọng hơn kiếm tiền.", "Hãy là một trader tỉnh táo nhất.", "Cơ hội còn rất nhiều, đừng vội vàng.", "Tích tiểu thành đại, chúc anh em may mắn.", "Thị trường luôn đúng, hãy thích nghi.", "Chúc anh em gặt hái được nhiều lợi nhuận.", "Đừng bao giờ all-in vào một vị thế.", "Kiên nhẫn chờ đợi điểm vào đẹp nhất.", "Thành quả sẽ xứng đáng với nỗ lực.", "Hẹn gặp anh em ở những kèo tiếp theo.", "Giữ vững tâm lý trong mọi hoàn cảnh.", "Đầu tư là một cuộc đua dài hạn.", "Cùng nhau chinh phục thị trường crypto.", "Luôn học hỏi sau mỗi lần giao dịch.", "Chiến thắng thuộc về người có kế hoạch.", "Tự tin vào phân tích của bản thân.", "Chúc mọi người một ngày xanh sàn.", "Dòng tiền sẽ về túi người kiên định.", "Hãy quản trị rủi ro thật chặt chẽ.", "Lợi nhuận bền vững là mục tiêu hàng đầu.", "Cùng xây dựng cộng đồng trade văn minh.", "Luôn sẵn sàng cho mọi biến động thị trường.", "Chúc anh em bội thu trong mùa này.", "Giao dịch có trách nhiệm với túi tiền.", "Hành trình tự do tài chính sắp bắt đầu.", "Tận hưởng niềm vui sau mỗi cú chốt lời.",
    "Hãy luôn giữ một cái đầu lạnh.", "Crypto là một cuộc chơi trí tuệ.", "Thành công không dành cho kẻ lười biếng.", "Học hỏi mỗi ngày để tiến xa hơn.", "Kỷ luật là sức mạnh lớn nhất.", "Giao dịch bằng lý trí, đừng bằng trái tim.", "Luôn đặt mục tiêu rõ ràng cho bản thân.", "Hẹn gặp lại các bạn ở mặt trăng.", "Chúc mọi người giao dịch thành công rực rỡ.", "Đừng để những biến động ngắn hạn làm phiền.", "Tầm nhìn dài hạn luôn mang lại quả ngọt.", "Quản lý rủi ro tốt là thắng một nửa.", "Hãy tận hưởng quá trình học hỏi.", "Chúc anh em có những quyết định sáng suốt.", "Mọi nỗ lực sẽ được đền đáp xứng đáng.", "Đừng bao giờ từ bỏ ước mơ tài chính.", "Hãy là người làm chủ cuộc chơi này.", "Lợi nhuận sẽ đến với người biết chờ đợi.", "Thị trường luôn hào phóng với người kỷ luật.", "Chúc may mắn và thắng lợi lớn.", "Luôn chuẩn bị cho những kịch bản xấu nhất.", "Hãy giữ cho mình một tâm thái bình thản.", "Thành công là một quá trình, không phải đích đến.", "Chúc anh em trade tốt và thắng lớn.", "Gặt hái lợi nhuận một cách bền vững.", "Đừng để lòng tham dẫn lối giao dịch.", "Chúc mọi người một mùa trading rực rỡ.", "Hãy tự tin vào chiến thuật của mình.", "Sự kiên trì luôn có cái giá xứng đáng.", "Hẹn gặp anh em ở những đỉnh cao mới.",
    "Giao dịch an toàn, lợi nhuận vững bền.", "Chúc anh em ngày mới trade đâu thắng đó.", "Giữ vững niềm tin vào con đường đã chọn.", "Hãy luôn là phiên bản tốt hơn mỗi ngày.", "Crypto cần kiến thức, không phải may mắn.", "Học cách chấp nhận và sửa sai nhanh chóng.", "Chúc mọi người bội thu từ thị trường.", "Hãy quản lý vốn như một người chuyên nghiệp.", "Sự bình tĩnh tạo nên sự khác biệt.", "Hẹn gặp lại ở các phân tích sau.", "Chúc anh em nhiều xanh và ít đỏ.", "Kế hoạch rõ ràng, hành động dứt khoát.", "Đừng để thị trường đánh lừa cảm giác.", "Chúc mọi người gặt hái nhiều thành công.", "Hành trình này rất dài, hãy giữ sức.", "Luôn tập trung vào mục tiêu của bạn.", "Lợi nhuận sẽ theo sau sự chuyên nghiệp.", "Chúc anh em luôn tỉnh táo trong mọi lệnh.", "Hãy tin vào bản thân và kế hoạch của mình.", "Hẹn gặp lại ở đỉnh cao vinh quang.",
    "Vững bước trên con đường crypto.", "Chúc mọi người trade thuận buồm xuôi gió.", "Luôn học hỏi và tích lũy kinh nghiệm.", "Cơ hội luôn mở ra cho người kiên trì.", "Đừng quên mục tiêu ban đầu của bạn.", "Chúc một ngày trading đầy khởi sắc.", "Sự chuẩn bị kỹ lưỡng mang lại kết quả tốt.", "Luôn kỷ luật và giữ vững tâm lý.", "Hẹn gặp lại ở những cột mốc mới.", "Chúc mừng anh em đã chốt lời thành công."
];

const bigQuestions = [
    "Anh em đang hold mã nào bền bỉ nhất mùa này?", "Sàn nào phí giao dịch rẻ nhất hiện nay anh em?", "Bao giờ thì Altcoin Season thực sự bùng nổ?", "Có nên dùng đòn bẩy x100 lúc này không?", "Mọi người thường dùng ví lạnh loại nào?", "Kinh nghiệm tránh rug-pull là gì vậy?", "BTC lên 100k anh em sẽ làm gì đầu tiên?", "Làm sao để lọc kèo x100 giữa rừng rác?", "Anh em tin vào PTKT hay tin vào hệ tâm linh hơn?", "Dấu hiệu nào cho thấy một dự án sắp sập?", "Có ai từng cháy tài khoản vì fomo memecoin chưa?", "Thị trường này kiến thức hay may mắn quan trọng hơn?", "Làm thế nào để ngủ ngon khi đang gồng lỗ?", "KOL nào anh em thấy phán chuẩn nhất hiện nay?", "Chiến thuật DCA còn hiệu quả trong mùa này không?", "Anh em nghĩ sao về tương lai của Layer 2?", "Khi nào thì nên chốt gốc và để lãi chạy?", "Ai đang dùng bot trade tự động xin ít review?", "Làm giàu từ crypto cần bao nhiêu vốn là đủ?", "Điều gì khiến anh em sợ hãi nhất lúc này?", "Crypto đã thay đổi cuộc sống của anh em thế nào?", "Nếu chỉ được chọn 1 đồng coin duy nhất để hold 10 năm?", "Có nên bỏ việc để làm trader toàn thời gian?", "Làm sao để nhận biết sớm sóng thần của thị trường?", "Tại sao chúng ta thường mua đỉnh bán đáy?", "Nên học trade từ đâu cho người mới bắt đầu?", "Anh em nghĩ sao về các kèo airdrop hiện nay?", "Lợi nhuận lớn nhất anh em từng đạt được là bao nhiêu?", "Chia sẻ một bài học xương máu khi trade đi.", "Thị trường này có thực sự là cờ bạc không?",
    "Anh em có dùng AI để phân tích chart không?", "Tâm lý giao dịch quan trọng thế nào đối với bạn?", "Dự án nào đang bị cộng đồng đánh giá thấp nhất?", "Có nên tin vào những tin đồn trên X không?", "Kỹ năng nào một trader cần có nhất?", "Làm sao để thoát khỏi cái bẫy cảm xúc khi trade?", "Anh em thường giao dịch vào khung giờ nào?", "Công cụ phân tích nào bạn không thể thiếu?", "Cách để cân bằng cuộc sống và giao dịch crypto?", "Tại sao 90% trader mới thường bị thua lỗ?", "Bạn nghĩ gì về sự can thiệp pháp lý vào crypto?", "Đâu là sai lầm lớn nhất bạn từng mắc phải?", "Làm sao để bảo mật tài khoản tốt nhất?", "Mô hình nến nào có độ tin cậy cao nhất?", "Bạn có đang hold stablecoin để chờ sập không?", "Cảm giác của bạn khi lỡ một kèo x10?", "Làm sao để tìm được những hidden gem sớm nhất?", "Bạn ưu tiên bảo toàn vốn hay lợi nhuận cao?", "Làm thế nào để duy trì kỷ luật giao dịch?", "Bạn có đang theo dõi cá voi không?", "Thị trường crypto sẽ đi về đâu trong 5 năm tới?", "Bạn có tham gia các nhóm tín hiệu thu phí không?", "Làm sao để lọc bỏ nhiễu trên đồ thị?", "Bạn nghĩ gì về trào lưu SocialFi hiện nay?", "Cách để tối ưu hóa lợi nhuận trong uptrend?", "Bạn có đang tích lũy thêm coin lúc này không?", "Làm thế nào để tránh bị hack ví?", "Bạn thích phong cách trade scalping hay swing?", "Đâu là đồng coin bạn hối tiếc vì đã bán sớm?", "Anh em Square có dự định gì cho tết này chưa?",
    "Làm sao để không bị fomo khi thị trường xanh?", "Bạn thường cắt lỗ ở mức bao nhiêu phần trăm?", "Có nên tin vào phân tích của các quỹ lớn?", "Làm thế nào để quản lý danh mục hiệu quả?", "Bạn nghĩ gì về xu hướng NFT hiện nay?", "Cách để nhận biết một đợt sóng điều chỉnh?", "Bạn có sử dụng đòn bẩy trong giao dịch không?", "Tại sao chúng ta thường hối tiếc sau khi chốt lời?", "Làm sao để giữ tâm lý vững vàng khi bão tới?", "Bạn có chia sẻ kèo cho bạn bè không?", "Làm thế nào để tìm hiểu về một dự án mới?", "Bạn nghĩ gì về tương lai của Bitcoin?", "Sự khác biệt giữa trader và holder là gì?", "Bạn có dùng các công cụ bot tín hiệu không?", "Làm sao để tối ưu hóa thuế crypto?", "Bạn nghĩ gì về việc đào coin hiện nay?", "Cách để duy trì sự tập trung khi trading?", "Bạn thường học hỏi kinh nghiệm từ đâu?", "Làm sao để tránh các sàn giao dịch lừa đảo?", "Bạn có đang lạc quan về thị trường lúc này không?", "Điều gì giúp bạn trụ lại thị trường lâu đến vậy?", "Bạn có kế hoạch nghỉ hưu sớm từ crypto không?", "Cách để vượt qua nỗi sợ hãi khi vào lệnh?", "Bạn nghĩ gì về vai trò của truyền thông trong crypto?", "Làm sao để xây dựng một chiến thuật trade riêng?", "Bạn thường dành bao nhiêu thời gian cho crypto mỗi ngày?", "Điều gì làm bạn hứng thú nhất ở thị trường này?", "Bạn có đang sử dụng các sàn phi tập trung không?", "Làm sao để nhận biết một xu hướng đang kết thúc?", "Bạn có lời khuyên nào cho người mới không?",
    "Anh em nghĩ sao về việc staking coin dài hạn?", "Làm sao để không bị tâm lý đám đông chi phối?", "Bạn có đang theo dõi các chỉ số vĩ mô không?", "Cách để nhận diện một cú lừa thanh khoản?", "Bạn có tin vào các chu kỳ 4 năm của Bitcoin?", "Làm thế nào để giữ an toàn cho tiền của bạn?", "Bạn nghĩ gì về các dự án memecoin hiện nay?", "Cách để rèn luyện tính kiên nhẫn khi trading?", "Bạn có đang học thêm về lập trình blockchain không?", "Tại sao đa số mọi người đều mất tiền ở crypto?", "Bạn có tin rằng crypto sẽ thay thế tiền pháp định?", "Cách để tận hưởng lợi nhuận từ trading?", "Bạn có thường xuyên cập nhật tin tức crypto không?", "Điều gì khiến bạn tin tưởng vào mã mình đang hold?", "Làm sao để không bị stress khi thị trường sập?", "Bạn có đang tham gia vào các DAO không?", "Cách để đánh giá uy tín của một đội ngũ dự án?", "Bạn nghĩ gì về tương lai của web3?", "Làm sao để giữ được lợi nhuận trong dài hạn?", "Bạn có đang hold coin nào ở ví cá nhân không?", "Điều gì quan trọng nhất khi bắt đầu một ngày trade?", "Bạn có thường xuyên thay đổi chiến thuật không?", "Làm sao để nhận biết vùng đỉnh của thị trường?", "Bạn có đang cảm thấy áp lực từ crypto không?", "Cách để giữ cho máy tính của bạn an toàn khi trade?", "Bạn nghĩ gì về sự bùng nổ của các layer 1 mới?", "Làm sao để tìm thấy niềm vui trong trading?", "Bạn có đang dùng các công cụ phân tích on-chain không?", "Điều gì khiến bạn quyết định vào một lệnh trade?", "Bạn có kế hoạch gì khi thị trường bước vào downtrend?",
    "Anh em đang hold mã nào bền bỉ nhất mùa này?", "Sàn nào phí giao dịch rẻ nhất hiện nay anh em?", "Bao giờ thì Altcoin Season thực sự bùng nổ?", "Có nên dùng đòn bẩy x100 lúc này không?", "Mọi người thường dùng ví lạnh loại nào?", "Kinh nghiệm tránh rug-pull là gì vậy?", "BTC lên 100k anh em sẽ làm gì đầu tiên?", "Làm sao để lọc kèo x100 giữa rừng rác?", "Anh em tin vào PTKT hay tin vào hệ tâm linh hơn?", "Dấu hiệu nào cho thấy một dự án sắp sập?", "Có ai từng cháy tài khoản vì fomo memecoin chưa?", "Thị trường này kiến thức hay may mắn quan trọng hơn?", "Làm thế nào để ngủ ngon khi đang gồng lỗ?", "KOL nào anh em thấy phán chuẩn nhất hiện nay?", "Chiến thuật DCA còn hiệu quả trong mùa này không?", "Anh em nghĩ sao về tương lai của Layer 2?", "Khi nào thì nên chốt gốc và để lãi chạy?", "Ai đang dùng bot trade tự động xin ít review?", "Làm giàu từ crypto cần bao nhiêu vốn là đủ?", "Điều gì khiến anh em sợ hãi nhất lúc này?", "Crypto đã thay đổi cuộc sống của anh em thế nào?", "Nếu chỉ được chọn 1 đồng coin duy nhất để hold 10 năm?", "Có nên bỏ việc để làm trader toàn thời gian?", "Làm sao để nhận biết sớm sóng thần của thị trường?", "Tại sao chúng ta thường mua đỉnh bán đáy?", "Nên học trade từ đâu cho người mới bắt đầu?", "Anh em nghĩ sao về các kèo airdrop hiện nay?", "Lợi nhuận lớn nhất anh em từng đạt được là bao nhiêu?", "Chia sẻ một bài học xương máu khi trade đi.", "Thị trường này có thực sự là cờ bạc không?",
    "Anh em có dùng AI để phân tích chart không?", "Tâm lý giao dịch quan trọng thế nào đối với bạn?", "Dự án nào đang bị cộng đồng đánh giá thấp nhất?", "Có nên tin vào những tin đồn trên X không?", "Kỹ năng nào một trader cần có nhất?", "Làm sao để thoát khỏi cái bẫy cảm xúc khi trade?", "Anh em thường giao dịch vào khung giờ nào?", "Công cụ phân tích nào bạn không thể thiếu?", "Cách để cân bằng cuộc sống và giao dịch crypto?", "Tại sao 90% trader mới thường bị thua lỗ?", "Bạn nghĩ gì về sự can thiệp pháp lý vào crypto?", "Đâu là sai lầm lớn nhất bạn từng mắc phải?", "Làm sao để bảo mật tài khoản tốt nhất?", "Mô hình nến nào có độ tin cậy cao nhất?", "Bạn có đang hold stablecoin để chờ sập không?", "Cảm giác của bạn khi lỡ một kèo x10?", "Làm sao để tìm được những hidden gem sớm nhất?", "Bạn ưu tiên bảo toàn vốn hay lợi nhuận cao?", "Làm thế nào để duy trì kỷ luật giao dịch?", "Bạn có đang theo dõi cá voi không?", "Thị trường crypto sẽ đi về đâu trong 5 năm tới?", "Bạn có tham gia các nhóm tín hiệu thu phí không?", "Làm sao để lọc bỏ nhiễu trên đồ thị?", "Bạn nghĩ gì về trào lưu SocialFi hiện nay?", "Cách để tối ưu hóa lợi nhuận trong uptrend?", "Bạn có đang tích lũy thêm coin lúc này không?", "Làm thế nào để tránh bị hack ví?", "Bạn thích phong cách trade scalping hay swing?", "Đâu là đồng coin bạn hối tiếc vì đã bán sớm?", "Anh em Square có dự định gì cho tết này chưa?",
    "Làm sao để không bị fomo khi thị trường xanh?", "Bạn thường cắt lỗ ở mức bao nhiêu phần trăm?", "Có nên tin vào phân tích của các quỹ lớn?", "Làm thế nào để quản lý danh mục hiệu quả?", "Bạn nghĩ gì về xu hướng NFT hiện nay?", "Cách để nhận biết một đợt sóng điều chỉnh?", "Bạn có sử dụng đòn bẩy trong giao dịch không?", "Tại sao chúng ta thường hối tiếc sau khi chốt lời?", "Làm sao để giữ tâm lý vững vàng khi bão tới?", "Bạn có chia sẻ kèo cho bạn bè không?", "Làm thế nào để tìm hiểu về một dự án mới?", "Bạn nghĩ gì về tương lai của Bitcoin?", "Sự khác biệt giữa trader và holder là gì?", "Bạn có dùng các công cụ bot tín hiệu không?", "Làm sao để tối ưu hóa thuế crypto?", "Bạn nghĩ gì về việc đào coin hiện nay?", "Cách để duy trì sự tập trung khi trading?", "Bạn thường học hỏi kinh nghiệm từ đâu?", "Làm sao để tránh các sàn giao dịch lừa đảo?", "Bạn có đang lạc quan về thị trường lúc này không?", "Điều gì giúp bạn trụ lại thị trường lâu đến vậy?", "Bạn có kế hoạch nghỉ hưu sớm từ crypto không?", "Cách để vượt qua nỗi sợ hãi khi vào lệnh?", "Bạn nghĩ gì về vai trò của truyền thông trong crypto?", "Làm sao để xây dựng một chiến thuật trade riêng?", "Bạn thường dành bao nhiêu thời gian cho crypto mỗi ngày?", "Điều gì làm bạn hứng thú nhất ở thị trường này?", "Bạn có đang sử dụng các sàn phi tập trung không?", "Làm sao để nhận biết một xu hướng đang kết thúc?", "Bạn có lời khuyên nào cho người mới không?",
    "Anh em nghĩ sao về việc staking coin dài hạn?", "Làm sao để không bị tâm lý đám đông chi phối?", "Bạn có đang theo dõi các chỉ số vĩ mô không?", "Cách để nhận diện một cú lừa thanh khoản?", "Bạn có tin vào các chu kỳ 4 năm của Bitcoin?", "Làm thế nào để giữ an toàn cho tiền của bạn?", "Bạn nghĩ gì về các dự án memecoin hiện nay?", "Cách để rèn luyện tính kiên nhẫn khi trading?", "Bạn có đang học thêm về lập trình blockchain không?", "Tại sao đa số mọi người đều mất tiền ở crypto?", "Bạn có tin rằng crypto sẽ thay thế tiền pháp định?", "Cách để tận hưởng lợi nhuận từ trading?", "Bạn có thường xuyên cập nhật tin tức crypto không?", "Điều gì khiến bạn tin tưởng vào mã mình đang hold?", "Làm sao để không bị stress khi thị trường sập?", "Bạn có đang tham gia vào các DAO không?", "Cách để đánh giá uy tín của một đội ngũ dự án?", "Bạn nghĩ gì về tương lai của web3?", "Làm sao để giữ được lợi nhuận trong dài hạn?", "Bạn có đang hold coin nào ở ví cá nhân không?", "Điều gì quan trọng nhất khi bắt đầu một ngày trade?", "Bạn có thường xuyên thay đổi chiến thuật không?", "Làm sao để nhận biết vùng đỉnh của thị trường?", "Bạn có đang cảm thấy áp lực từ crypto không?", "Cách để giữ cho máy tính của bạn an toàn khi trade?", "Bạn nghĩ gì về sự bùng nổ của các layer 1 mới?", "Làm sao để tìm thấy niềm vui trong trading?", "Bạn có đang dùng các công cụ phân tích on-chain không?", "Điều gì khiến bạn quyết định vào một lệnh trade?", "Bạn có kế hoạch gì khi thị trường bước vào downtrend?",
    "Chào buổi sáng anh em, hôm nay định trade mã gì chưa?", "Thị trường này có làm anh em mệt mỏi không?", "Sắp tới có dự án nào ra mắt mà anh em quan tâm không?", "Làm sao để cân đối vốn giữa spot và future?", "Anh em có ai từng mất tiền vì quên private key chưa?", "Bao nhiêu phần trăm tài sản của bạn đang ở crypto?", "Làm thế nào để phân biệt kèo thật và kèo lùa gà?", "Bạn nghĩ gì về tương lai của các sàn tập trung?", "Cách để giữ sức khỏe tốt khi thức đêm canh chart?", "Cuối tuần anh em thường nghỉ ngơi hay vẫn trade?"
];

// ==========================================
// 3. LOGIC TRÌNH DUYỆT & GIẢ LẬP
// ==========================================

async function initBrowser(show = false) {
    if (context) {
        try { await context.pages(); return context; } catch (e) { context = null; }
    }
    killStaleChromium(); // Diệt chrome kẹt trước khi mở mới
    context = await chromium.launchPersistentContext(userDataDir, {
        headless: !show,
        args: ['--disable-blink-features=AutomationControlled', '--no-sandbox']
    });
    return context;
}

async function ensureMainPage() {
    const ctx = await initBrowser(false);
    if (!mainPage || mainPage.isClosed()) {
        mainPage = await ctx.newPage();
        await mainPage.goto('https://www.binance.com/vi/square', { waitUntil: 'domcontentloaded', timeout: 60000 });
    }
    return mainPage;
}

async function postTaskWithForce() {
    if (!isRunning) return;

    try {
        let page = await ensureMainPage();
        let contentBody = "";

        // Tỷ lệ 1 bài thảo luận (Question) sau mỗi 4 bài tín hiệu (Signal)
        if (totalPosts > 0 && totalPosts % 5 === 0) {
            contentBody = bigQuestions[Math.floor(Math.random() * bigQuestions.length)];
        } else {
            if (coinQueue.length === 0) {
                const res = await axios.get('https://fapi.binance.com/fapi/v1/ticker/24hr');
                coinQueue = res.data.filter(c => c.symbol.endsWith('USDT')).map(c => ({
                    symbol: c.symbol.replace('USDT', ''), price: c.lastPrice
                })).sort(() => 0.5 - Math.random());
            }
            const currentCoin = coinQueue.shift();
            const intro = bigIntros[Math.floor(Math.random() * bigIntros.length)].replace("COIN", currentCoin.symbol);
            const body = bigBodies[Math.floor(Math.random() * bigBodies.length)];
            const closing = bigClosings[Math.floor(Math.random() * bigClosings.length)];
            
            contentBody = `${intro}\n\n${body}\n\n📍 GIÁ HIỆN TẠI: ${parseFloat(currentCoin.price)}\n\n${closing}\n\n$${currentCoin.symbol} #BinanceSquare #TradingSignal`;
        }

        const textbox = page.locator('div[contenteditable="true"]').first();
        await textbox.waitFor({ state: 'visible' });
        await textbox.click();
        await page.keyboard.press('Control+A');
        await page.keyboard.press('Backspace');

        // Gõ phím kiểu người thật (Random delay từng phím)
        for (const char of contentBody) {
            await page.keyboard.type(char, { delay: Math.floor(Math.random() * 60) + 20 });
        }

        const postBtn = page.locator('button').filter({ hasText: /^Đăng$|^Post$/ }).last();
        if (await postBtn.isEnabled()) {
            await postBtn.click();
            totalPosts++;
            console.log(`✅ [${new Date().toLocaleTimeString()}] Đã đăng thành công bài số: ${totalPosts}`);
            // Nghỉ 2-4 phút
            await new Promise(r => setTimeout(r, (Math.floor(Math.random() * 120) + 120) * 1000));
        }
    } catch (err) {
        console.log(`❌ Lỗi: ${err.message}`);
        context = null; // Để reset trình duyệt vòng sau
        await new Promise(r => setTimeout(r, 15000));
    }
    
    if (isRunning) postTaskWithForce();
}

// ==========================================
// 4. SERVER ROUTES & GIAO DIỆN
// ==========================================
const htmlIndex = `<!DOCTYPE html><html><head><title>Panel</title><style>body{background:#121212;color:#fff;text-align:center;font-family:sans-serif;padding-top:100px;}button{padding:20px;margin:10px;font-weight:bold;cursor:pointer;border-radius:10px;border:none;}.start{background:#28a745;color:#fff;}.stop{background:#dc3545;color:#fff;}.login{background:#ffc107;}</style></head><body><h1>🤖 Binance Square Bot</h1><button class="login" onclick="location.href='/login'">1. ĐĂNG NHẬP (HIỆN CHROME)</button><br><button class="start" onclick="fetch('/start')">2. BẮT ĐẦU CHẠY</button><button class="stop" onclick="fetch('/stop')">DỪNG LẠI</button><div id="st"></div><script>setInterval(()=>fetch('/stats').then(r=>r.json()).then(d=>{document.getElementById('st').innerHTML='<h2>Đã đăng: '+d.totalPosts+' bài</h2><p>Trạng thái: '+(d.isRunning?'Đang chạy':'Đang dừng')+'</p>'}),2000)</script></body></html>`;

app.get('/', (req, res) => res.send(htmlIndex));
app.get('/stats', (req, res) => res.json({ totalPosts, isRunning }));
app.get('/start', (req, res) => { if (!isRunning) { isRunning = true; postTaskWithForce(); } res.json({s:1}); });
app.get('/stop', (req, res) => { isRunning = false; res.json({s:1}); });
app.get('/login', async (req, res) => {
    if (context) await context.close();
    const ctx = await initBrowser(true);
    await (await ctx.newPage()).goto('https://www.binance.com/vi/square');
    res.send("<h2>Chrome đã mở. Hãy đăng nhập xong rồi quay lại đây bấm Bắt đầu chạy.</h2>");
});

app.listen(port, '0.0.0.0', () => console.log(`🚀 Server live tại port ${port}`));
