// === Cấu hình Bot ===
// ...
// ĐÃ SỬA: Ngưỡng funding rate DƯƠNG tối thiểu để xem xét (từ -0.01 xuống 0.0001)
// Cần funding rate dương để mở lệnh LONG
const MIN_FUNDING_RATE_THRESHOLD = 0.0001;
// ...
